# Generated by Django 4.1.13 on 2025-04-22 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "original_filepath",
                    models.FileField(upload_to="invoices/original_files/"),
                ),
                ("abf_filename", models.CharField(max_length=50, unique=True)),
                (
                    "new_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "new_filepath",
                    models.FileField(
                        blank=True, null=True, upload_to="invoices/converted_files/"
                    ),
                ),
                (
                    "transaction_document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CI", "Commercial Invoice"),
                            ("BS", "Balance Sheet"),
                            ("CC", "Credit Card Statement"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
