# Generated by Django 4.1.13 on 2025-04-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="abf_filename",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
