# Generated by Django 4.1.13 on 2025-04-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_uploadedfile_abf_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.CharField(max_length=255)),
                ("lang", models.CharField(default="en", max_length=5)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
