# Generated by Django 4.1.13 on 2025-04-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_chartofaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chartofaccount",
            name="description",
        ),
        migrations.RemoveField(
            model_name="chartofaccount",
            name="lang",
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="activation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="category",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="classification",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="desc_long_de",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="desc_long_en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="desc_short_de",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="desc_short_en",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="ledger",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="chartofaccount",
            name="statement",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
