# Generated by Django 4.1.13 on 2025-04-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_remove_chartofaccount_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="COAClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("group", models.CharField(blank=True, max_length=50, null=True)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "COA Classification",
                "verbose_name_plural": "COA Classifications",
                "ordering": ["code"],
            },
        ),
        migrations.RenameField(
            model_name="chartofaccount",
            old_name="category",
            new_name="coa_classification",
        ),
        migrations.RemoveField(
            model_name="chartofaccount",
            name="classification",
        ),
    ]
