# Generated by Django 4.1.13 on 2025-05-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_coaclassification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chartofaccount",
            name="coa_classification",
            field=models.ForeignKey(
                blank=True,
                db_column="coa_classification",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="chart_accounts",
                to="accounting.coaclassification",
                to_field="code",
            ),
        ),
    ]
