# Generated by Django 4.1.13 on 2025-05-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0007_transactiondocument_transactionlineitem_supplier_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Supplier",
        ),
    ]
