# Generated by Django 4.1.13 on 2025-05-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_delete_supplier"),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Counterparty',
            new_name='Entity',
        ),
        # 만약 테이블 이름도 명시적으로 변경하고 싶다면 (보통 Django가 모델명에 맞춰 자동으로 변경)
        # migrations.AlterModelTable(
        # name='Entity',
        # table='새로운_테이블명_entity', # 예: your_app_name_entity
        # ),
    ]
