# Generated by Django 4.1.13 on 2025-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_rename_counterparty_to_entity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entity",
            options={"verbose_name": "Entity", "verbose_name_plural": "Entities"},
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="cp_bank_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="cp_bank_account_no",
            new_name="bank_account_no",
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="cp_bank_name",
            new_name="bank_address",
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="cp_contact_person_phone",
            new_name="bank_bic",
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="cp_bank_owner",
            new_name="bank_name",
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="cp_contact_person_name",
            new_name="contact_person_name",
        ),
        migrations.RenameField(
            model_name="entity",
            old_name="cp_phone",
            new_name="contact_person_phone",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_address",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_bank_bic",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_bank_iban",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_contact_person_email",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_country",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_email",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_id_parsed",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_name",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_postcode",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_regi_no",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_tax_no",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="cp_vat_no",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="transaction_document",
        ),
        migrations.AddField(
            model_name="entity",
            name="bank_iban",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="bank_owner",
            field=models.CharField(
                blank=True,
                help_text="Bank account holder name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="contact_person_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="entity_role",
            field=models.CharField(
                blank=True,
                choices=[("issuer", "Issuer"), ("receiver", "Receiver")],
                help_text="Role of this entity in a transaction (e.g., issuer or receiver). This might be contextual per transaction.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Company or person name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="postcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="regi_no",
            field=models.CharField(
                blank=True,
                help_text="Registration number (사업자등록번호 등)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="tax_no",
            field=models.CharField(
                blank=True, help_text="Tax number", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="vat_no",
            field=models.CharField(
                blank=True, help_text="VAT number", max_length=100, null=True
            ),
        ),
    ]
