# Generated by Django 4.1.13 on 2025-05-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_alter_entity_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactiondocument",
            options={
                "verbose_name": "Transaction Document",
                "verbose_name_plural": "Transaction Documents",
            },
        ),
        migrations.RemoveField(
            model_name="entity",
            name="entity_role",
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="issuer",
            field=models.ForeignKey(
                blank=True,
                help_text="The issuer of this document.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_documents",
                to="accounting.entity",
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="main_trading_partner_role",
            field=models.CharField(
                blank=True,
                choices=[("issuer", "Issuer"), ("receiver", "Receiver")],
                help_text="Indicates which party is considered the main trading partner from the perspective of the system user.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="receiver",
            field=models.ForeignKey(
                blank=True,
                help_text="The receiver of this document.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_documents",
                to="accounting.entity",
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="transaction_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="entity",
            name="regi_no",
            field=models.CharField(
                blank=True,
                help_text="Registration number (e.g., business registration number), should be unique if possible",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="cp_memo",
            field=models.TextField(
                blank=True, help_text="Counterparty memo.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                help_text="Type of the document (e.g., invoice, credit_note).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="invoice_no",
            field=models.CharField(
                blank=True, help_text="Invoice number.", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="issuance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="net_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Total net amount of the document.",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="payment_terms",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="prepayment",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="total_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Total amount due.",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="vat_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Total VAT amount of the document.",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="vat_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="VAT rate (e.g., 10.00 for 10%).",
                max_digits=5,
                null=True,
            ),
        ),
    ]
