# Generated by Django 4.1.13 on 2025-05-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_alter_transactiondocument_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactionlineitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Transaction Line Item",
                "verbose_name_plural": "Transaction Line Items",
            },
        ),
        migrations.RemoveField(
            model_name="transactionlineitem",
            name="line_item_net_amount",
        ),
        migrations.RemoveField(
            model_name="transactionlineitem",
            name="transaction_document",
        ),
        migrations.AddField(
            model_name="transactionlineitem",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Total amount for this line item (quantity * unit_price).",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transactionlineitem",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="The transaction document this line item belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="accounting.transactiondocument",
            ),
        ),
        migrations.AlterField(
            model_name="transactionlineitem",
            name="article_no",
            field=models.CharField(
                blank=True,
                help_text="Article number or code.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlineitem",
            name="line_item_id_parsed",
            field=models.CharField(
                blank=True,
                help_text="Parsed line item ID, if any.",
                max_length=255,
                null=True,
            ),
        ),
    ]
