# Generated by Django 4.1.13 on 2025-05-14 01:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_alter_transactionlineitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="entity_general_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("issuer", "Issuer"),
                    ("receiver", "Receiver"),
                    ("both", "Both Issuer and Receiver"),
                    ("other", "Other/Not Specified"),
                ],
                help_text="The general role of this entity (e.g., primarily an issuer, receiver, or can be both). This is a characteristic of the entity itself.",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="accounting_transaction_doc_type",
            field=models.CharField(
                blank=True,
                help_text="Specific type of the transaction document for accounting purposes (e.g., Standard Invoice, Debit Memo).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="accounting_transaction_document_date",
            field=models.DateField(
                blank=True,
                help_text="Date relevant to the transaction itself, as recognized by accounting (e.g., contract date, service completion date for accounting).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="booking_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the transaction was booked into the accounting system.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="booking_document_no",
            field=models.CharField(
                blank=True,
                help_text="Booking Document Number, assigned during accounting entry.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="closing_period",
            field=models.IntegerField(
                blank=True,
                help_text="The accounting closing period (month, 1-12) for this transaction.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="ledger_standard",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IFRS", "International Financial Reporting Standards"),
                    ("K-GAAP", "Korean Generally Accepted Accounting Principles"),
                    (
                        "US-GAAP",
                        "United States Generally Accepted Accounting Principles",
                    ),
                    ("OTHER", "Other"),
                ],
                help_text="The accounting ledger standard applied to this transaction.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="document_type",
            field=models.CharField(
                blank=True,
                help_text="Type of the document (e.g., invoice, credit_note) from OCR/parsing.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="issuance_date",
            field=models.DateField(
                blank=True,
                help_text="Date when the document was issued (e.g., invoice date).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactiondocument",
            name="main_trading_partner_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("issuer", "Issuer"),
                    ("receiver", "Receiver"),
                    ("both", "Both Issuer and Receiver"),
                    ("other", "Other/Not Specified"),
                ],
                help_text="Indicates which party is considered the main trading partner.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gl_account_no",
                    models.CharField(
                        help_text="GL Account No. (General Ledger Account Number).",
                        max_length=50,
                    ),
                ),
                (
                    "gl_account_description",
                    models.CharField(
                        blank=True,
                        help_text="GL Account Description.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "position_no",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Position or line number for ordering within the document's details.",
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="Currency for the amount in this line. If blank, may inherit from parent document.",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Amount for this detail line. Could be debit or credit.",
                        max_digits=19,
                    ),
                ),
                (
                    "tax_code",
                    models.CharField(
                        blank=True,
                        help_text="Tax code relevant to this line item.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional description for this transaction detail line.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_document",
                    models.ForeignKey(
                        help_text="The main transaction document this detail line belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="accounting.transactiondocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Detail",
                "verbose_name_plural": "Transaction Details",
                "ordering": ["transaction_document", "position_no", "id"],
            },
        ),
    ]
