# Generated by Django 4.1.13 on 2025-05-14 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0013_entity_entity_general_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactiondocument",
            name="accounting_transaction_document_date",
        ),
    ]
