# Generated by Django 4.1.13 on 2025-05-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0014_remove_transactiondocument_accounting_transaction_document_date",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiondetail",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[("debit", "Debit"), ("credit", "Credit")],
                help_text="Indicates if this line is a Debit or Credit entry.",
                max_length=10,
                null=True,
            ),
        ),
    ]
