# Generated by Django 4.1.13 on 2025-05-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_transactiondetail_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiondocument",
            name="anomaly_memo",
            field=models.TextField(
                blank=True,
                help_text="Notes on any detected anomalies, exceptions, or inconsistencies found during invoice processing. Max 255 chars advised for prompt, but TextField allows more.",
                null=True,
            ),
        ),
    ]
