# Generated by Django 4.1.13 on 2025-05-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0017_remove_uploadedfile_transaction_document_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transactiondocument",
            options={
                "ordering": [
                    "status",
                    "-confirmation_date",
                    "-issuance_date",
                    "-created_at",
                ],
                "verbose_name": "Transaction Document",
                "verbose_name_plural": "Transaction Documents",
            },
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="confirmation_date",
            field=models.DateField(
                blank=True, help_text="Date when the document was confirmed.", null=True
            ),
        ),
        migrations.AddField(
            model_name="transactiondocument",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("1_TO_CONFIRM", "To confirm"), ("2_CONFIRMED", "Confirmed")],
                default="1_TO_CONFIRM",
                help_text="Status of the transaction document.",
                max_length=15,
                null=True,
            ),
        ),
    ]
