# Generated by Django 4.1.13 on 2025-05-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0018_alter_transactiondocument_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="parsed_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
